#!/bin/bash
if [[ "${#}" -eq 2 ]] ; then
    /usr/KRB5/bin/kshell -c /root/twist/lib/trcp-wrap "$1" "$2"
else
    echo "Please check your syntax."
    echo "\$1 should be LOCAL_FILE."
    echo "\$2 should be [LIST or HOST or all]:DESTINATION_PATH."
    exit 3
fi
exit 0
